config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :brands
  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/search_history'

  get 'ranking/show'

  devise_for :users
  resources :users
  
  resources :keywords
  get 'nokogiri/search'

  get 'nokogiri/search_result'

   root 'nokogiri#search'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name_cn, :name_jp, :portfolio, :introduction, :image_url, :creation_time, :site_address)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_cn %><br>
    <%= f.text_field :name_cn %>
  </div>
  <div class="field">
    <%= f.label :name_jp %><br>
    <%= f.text_field :name_jp %>
  </div>
  <div class="field">
    <%= f.label :portfolio %><br>
    <%= f.text_field :portfolio %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br>
    <%= f.text_area :introduction %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :creation_time %><br>
    <%= f.date_select :creation_time %>
  </div>
  <div class="field">
    <%= f.label :site_address %><br>
    <%= f.text_field :site_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<div class="container">
          <div class="row" style=" margin:20px">  
            <div class="col-xs-12">
                <button class="btn btn-small " data-toggle="portfilter" data-target="all">
                    全部
                </button>
                <button class="btn btn-small btn-danger" data-toggle="portfilter" data-target="化妆品">
                    化妆品
                </button>
                <button class="btn btn-small btn-danger" data-toggle="portfilter" data-target="母婴">
                    母婴
                </button>
                <button class="btn btn-small btn-danger" data-toggle="portfilter" data-target="电子">
                    电子
                </button>
            </div>
          </div>  
               


                        <% @brands.each do |brand| %>
                           
                           <div class="col-md-4" data-tag='<%= brand.portfolio %>'>
                                    <div class="box">                           
                                        <div class="icon">
                                        
                                            <div class="image"><i class="fa ">logo</i></div>
                                            <div class="info">
                                                <h3 class="title"><%= brand.name_cn %></h3>
                                                <p>
                                                    <%= brand.introduction %>
                                                    <%= brand.portfolio %>
                                                </p>
                                                <div class="more">
                                                    <a href="#" title="Title Link">
                                                        更多信息 <i class="fa fa-angle-double-right"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="space"></div>

                                    </div> 
                            </div>
                            
                        <% end %> 
            
            
</div>




<p id="notice"><%= notice %></p>

<h1>Listing Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name cn</th>
      <th>Name jp</th>
      <th>Introduction</th>
      <th>Image url</th>
      <th>Creation time</th>
      <th>Site address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name_cn %></td>
        <td><%= brand.name_jp %></td>
        <td><%= brand.introduction %></td>
        <td><%= brand.image_url %></td>
        <td><%= brand.creation_time %></td>
        <td><%= brand.site_address %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name cn:</strong>
  <%= @brand.name_cn %>
</p>

<p>
  <strong>Name jp:</strong>
  <%= @brand.name_jp %>
</p>

<p>
  <strong>Name jp:</strong>
  <%= @brand.portfolio %>
</p>

<p>
  <strong>Introduction:</strong>
  <%= @brand.introduction %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @brand.image_url %>
</p>

<p>
  <strong>Creation time:</strong>
  <%= @brand.creation_time %>
</p>

<p>
  <strong>Site address:</strong>
  <%= @brand.site_address %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>