config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories
  resources :brands
  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/search_history'

  get 'ranking/show'

  devise_for :users
  resources :users
  
  resources :keywords
  get 'nokogiri/search'

  get 'nokogiri/search_result'

   root 'nokogiri#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ikura" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>



  </head>
  <body>

  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top navbar-transparent">
    <div class="container">
         

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"> <div class="logo"><span class="color-1">iku</span>ra</div></a>
      </div>

      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          
              <li class="<%= 'active' if current_page?(nokogiri_search_path) %>">
              <%= link_to(nokogiri_search_path) do %>
                <i class="fa fa-home"></i>主页
              <% end %>
              </li>

              <li class="<%= 'active' if current_page?(brands_path) %>">
              <%= link_to(brands_path) do %>
                <i class="fa fa-gift" aria-hidden="true"></i>品牌
              <% end %>
              </li>

              <li class="<%= 'active' if current_page?(products_path) %>">
              <%= link_to(products_path) do %>
                <i class="fa fa-gift" aria-hidden="true"></i>日货百科
              <% end %>
              </li>

              <li class="<%= 'active' if current_page?(keywords_path) %>">
              <%= link_to(keywords_path) do %>
                <i class="fa fa-fire" aria-hidden="true"></i>热门搜索
              <% end %>
              </li>

              
              
              <% if signed_in? %>   
                  <li class="dropdown <%= 'active' if current_page?(nokogiri_search_result_path) %>">
                  <%= link_to(nokogiri_search_result_path,{class:"dropdown-toggle","data-toggle": "dropdown"}) do %>
                    <i class="fa fa-user fa-6" aria-hidden="true"></i>我的账户<b class="caret"></b>
                  <% end %>

                      <ul class="dropdown-menu">
                        <li><%= link_to "主页",current_user %></li>
                        <li><%= link_to "历史",users_search_history_path %></li>
                        <li><%= link_to "收藏",new_user_session_path %></li>

                        <li class="dropdown-header">--------------------</li>
                        <li><%= link_to "设置",edit_user_path(current_user) %></li>
                        <li><%= link_to "退出",destroy_user_session_path,html_options = { method: "delete"} %></li>
                      </ul>
                  </li>
              <% else %>
                  <li class="<%= 'active' if current_page?(new_user_registration_path) %>">
                  <%= link_to(new_user_registration_path) do %>
                    <i class="fa fa-user-plus" aria-hidden="true"></i>注册
                  <% end %>
                  </li>

                  <li class="<%= 'active' if current_page?(new_user_session_path) %>">
                  <%= link_to(new_user_session_path) do %>
                    <i class="fa fa-sign-in" aria-hidden="true"></i></i>登录
                  <% end %>
                  </li>
              <% end %>
        </ul>
      </div><!--/.nav-collapse -->
      
    </div>
  </div>
  <div id="clouds">

    <div class="container theme-showcase" >

      <%= bootswatch_flash %>

    
      <%= yield %>
    <div class="cloud x1"></div>
    <!-- Time for multiple clouds to dance around -->
    <div class="cloud x2"></div>
    <div class="cloud x3"></div>
    <div class="cloud x4"></div>
    <div class="cloud x5"></div>

    </div> <!-- /container -->
    
  </div>






  




    




  </body>
</html>